name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Test my first workflow
        run: echo "This is a test message for my first workflow."
        
